apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: 192.168.1.11:30500/sample-app:1baef2073f51e36717be1bbae580349fc81308dd
        ports:
        - containerPort: 80
