apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: 192.168.1.11:30500/sample-app:fa45ac22fed5de6471c01adcd4d03f97908aa2c9
        ports:
        - containerPort: 80
